spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql:3306/facticle?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: facticle_user
    password: Qwer1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
