spring:
  config:
    activate:
      on-profile: common

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul # 시간을 KTC로 설정
        format_sql: true
        #show_sql: true
        default_batch_fetch_size: 300 #ToMany관계에서 페이징 및 성능을 위한 옵션, 필요한 경우 개별 엔티티나 컬렉션에서 추가 설정

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.hibernate.SQL: debug
    org.springframework: WARN
    com.example.facticle: DEBUG

server:
  port: 8080  # 기본 포트 (필요하면 변경 가능)
