spring:
  config:
    activate:
      on-profile: test

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        timezone:
          default_storage: NORMALIZE # Hibernate 시간대 처리 방식 설정
        jdbc:
          time_zone: UTC # 시간을 UTC로 통일
        #show_sql: true
        default_batch_fetch_size: 300 #ToMany관계에서 페이징 및 성능을 위한 옵션, 필요한 경우 개별 엔티티나 컬렉션에서 추가 설정

  datasource:
    url: jdbc:mysql://localhost:3306/facticle?serverTimezone=UTC&characterEncoding=UTF-8
    username: facticle_user
    password: Qwer1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
