spring:
  config:
    activate:
      on-profile: common

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul # 시간을 KTC로 설정
        format_sql: true
        #show_sql: true
        default_batch_fetch_size: 300 #ToMany관계에서 페이징 및 성능을 위한 옵션, 필요한 경우 개별 엔티티나 컬렉션에서 추가 설정

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.hibernate.SQL: debug
    org.springframework: WARN
    com.example.facticle: DEBUG

server:
  port: 8080

jwt:
  #보안 상 노출되지 않는 것이 좋음 -> 추후 환경변수 등으로 관리
  #secret key는 쉘에서 openssl rand -base64 32 커맨드로 생성함, 서명화 알고리즘에서 성능이 빠른 HS256을 사용할 예정이므로 256 bit의 key를 생성
  secret: oRf96S6l4scYOnZpl747wPckC7FmrGbEPOvbVYZj8Lw=
  access-token-valid-time: 10000   # 30분, 10초
  refresh-token-valid-time: 30000 # 1일, 30초
